spring:
  profiles: 8001
server:
  port: 8001
---
spring:
  profiles: 8002
server:
  port: 8002
---
spring:
  profiles: 8003
server:
  port: 8003
---
spring:
  profiles: 8004
server:
  port: 8004
---

server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的数据脚本
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

### INFO
#info:
#  app:
#    name: @project.artifactId@
#    encoding: @project.build.sourceEncoding@
#    java:
#      source: @java.version@
#      target: @java.version@
#management:
#  security:
#    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:1234@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
