server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:1234@localhost:8761/eureka/
security:
  basic:
    enabled: true
  user:
    name: user
    password: 1234