server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:1234@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
